# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pim Derks
email: info@pimderks.com
description: > #
  Lorem ipsum dolor sit amet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pimderks.com" # the base hostname & protocol for your site
future: false

# Where things are
source: ./src/jekyll
destination: ./www
keep_files: [static]

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Scope
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Collections
collections:
  albums:
    output: "true"
    permalink: /music/albums/:title/